@props([
    'amount',
    'currency' => 'ILS',
    'successUrl' => '',
    'errorUrl' => '',
    'cancelUrl' => '',
    'language' => 'he',
    'topText' => '',
    'bottomText' => '',
    'logoUrl' => '',
    'hidePelecardLogo' => false,
    'showConfirmation' => false,
    'minPayments' => null,
    'maxPayments' => null,
    'shopNumber' => null,
    'actionType' => 'J2',
    'authNum' => '',
    'firstPayment' => '',
    'firstPaymentLock' => false,
    'minPaymentsForCredit' => '',
    'sapakNo' => '',
    'disabledPaymentNumbers' => '',
    'paramX' => '',
    'paramZ' => '', 
    'token' => null,
    'use3ds' => false,
    'width' => '100%',
    'height' => '600',
    // New Appearance Props
    'businessName' => '',
    'captionExpInput' => '',
    'confirmationLink' => '',
    'cssUrl' => '',
    'cvvImageUrl' => '',
    'disableZoom' => false,
    'hiddenPciLogo' => false,
    'hiddenSslSeal' => false,
    'forceTovCard' => false,
    'hideFields' => '',
    'idCvvInputType' => '',
    'logoAltText' => '',
    'numericInputMode' => '',
    'openConfirmationBoxInModal' => false,
    'placeholderCaptions' => false,
    'placeholderCcNumber' => '',
    'setFocus' => '',
    'showBrandLogo' => false,
    'showSubmitButton' => true,
    'showXParam' => false,
    'defaultTabButton' => '',
    'creditCardExpiryDateMinDays' => '',
    'textAfterConfirmationLink' => '',
    'textBeforeConfirmationLink' => '',
    'textOnConfirmationBox' => '',
    'splitCcNumber' => false,
    'userNoScalable' => false,
    // Behavior Props
    'addHolderNameToXParam' => false,
    'addRemarksToXParam' => false,
    'allowedBins' => '',
    'blockedBins' => '',
    'j5AsJ2ForBins' => false,
    'inputErrorDisplayByField' => false,
    'customErrorHandling' => '',
    'errorClass' => '',
    'requiredValidatedClass' => '',
    'userKey' => '',
    'takeIshurPopUp' => false,
    // Wallet Props
    'supportedCards' => '',
    'enableBit' => false,
    'bitBtnText' => '',
    'bitPopUpConfirmationText' => '',
    'googlePay' => false,
    'applePay' => false,
])

@php
    $client = app(\Yousefkadah\Pelecard\PelecardClient::class);
    $iframeHelper = new \Yousefkadah\Pelecard\IframeHelper($client);
    
    $paymentData = [
        'amount' => $amount,
        'currency' => $currency,
        'success_url' => $successUrl ?? route('pelecard.success'),
        'error_url' => $errorUrl ?? route('pelecard.error'),
        'cancel_url' => $cancelUrl ?? route('pelecard.cancel'),
        'language' => $language,
        'shop_number' => $shopNumber,
        'action_type' => $actionType,
        'auth_num' => $authNum,
        'first_payment' => $firstPayment,
        'first_payment_lock' => $firstPaymentLock,
        'min_payments_for_credit' => $minPaymentsForCredit,
        'sapak_no' => $sapakNo,
        'disabled_payment_numbers' => $disabledPaymentNumbers,
        'param_x' => $paramX ?? uniqid('pelecard_'),
        'param_z' => $paramZ,
        'top_text' => $topText,
        'bottom_text' => $bottomText,
        'logo_url' => $logoUrl,
        'hide_pelecard_logo' => $hidePelecardLogo ? '1' : '0',
        'show_confirmation' => $showConfirmation ? '1' : '0',
        'min_payments' => $minPayments,
        'max_payments' => $maxPayments,
        'token' => $token,
        'use_3ds' => $use3ds,
        // Appearance
        'business_name' => $businessName,
        'caption_exp_input' => $captionExpInput,
        'confirmation_link' => $confirmationLink,
        'css_url' => $cssUrl,
        'cvv_image_url' => $cvvImageUrl,
        'disable_zoom' => $disableZoom,
        'hidden_pci_logo' => $hiddenPciLogo,
        'hidden_ssl_seal' => $hiddenSslSeal,
        'force_tov_card' => $forceTovCard,
        'hide_fields' => $hideFields,
        'id_cvv_input_type' => $idCvvInputType,
        'logo_alt_text' => $logoAltText,
        'numeric_input_mode' => $numericInputMode,
        'open_confirmation_box_in_modal' => $openConfirmationBoxInModal,
        'placeholder_captions' => $placeholderCaptions,
        'placeholder_cc_number' => $placeholderCcNumber,
        'set_focus' => $setFocus,
        'show_brand_logo' => $showBrandLogo,
        'show_submit_button' => $showSubmitButton,
        'show_x_param' => $showXParam,
        'default_tab_button' => $defaultTabButton,
        'credit_card_expiry_date_min_days' => $creditCardExpiryDateMinDays,
        'text_after_confirmation_link' => $textAfterConfirmationLink,
        'text_before_confirmation_link' => $textBeforeConfirmationLink,
        'text_on_confirmation_box' => $textOnConfirmationBox,
        'split_cc_number' => $splitCcNumber,
        'user_no_scalable' => $userNoScalable,
        // Behavior
        'add_holder_name_to_x_param' => $addHolderNameToXParam,
        'add_remarks_to_x_param' => $addRemarksToXParam,
        'allowed_bins' => $allowedBins,
        'blocked_bins' => $blockedBins,
        'j5_as_j2_for_bins' => $j5AsJ2ForBins,
        'input_error_display_by_field' => $inputErrorDisplayByField,
        'custom_error_handling' => $customErrorHandling,
        'error_class' => $errorClass,
        'required_validated_class' => $requiredValidatedClass,
        'user_key' => $userKey,
        'take_ishur_pop_up' => $takeIshurPopUp,
        // Wallets
        'supported_cards' => $supportedCards,
        'enable_bit' => $enableBit,
        'bit_btn_text' => $bitBtnText,
        'bit_pop_up_confirmation_text' => $bitPopUpConfirmationText,
        'google_pay' => $googlePay,
        'apple_pay' => $applePay,
    ];
    
    $iframeHtml = $iframeHelper->generateIframe($paymentData, [
        'width' => $width,
        'height' => $height,
    ]);
@endphp

{!! $iframeHtml !!}
